### ISSUE TITLE
Incompatibility with RxJS 7.8.1

### ISSUE THREAD

**Issue by dsawali** [kwonoj/rx-sandbox#1059]
Hello there, 

I'm not sure if this repository is being actively maintained, but we use `rx-sandbox` in our repo to help test observables in RxJS.

It seems like after updating our RxJS version, our unit tests that were using `rx-sandbox` stopped working with this message in all the import locations:
```
    Cannot find module 'rxjs/internal/scheduler/AsyncAction' from '../../node_modules/rx-sandbox/dist/utils/coreInternalImport.js'

    Require stack:
      /Users/dsawali/Desktop/ecadlabs/taquito/node_modules/rx-sandbox/dist/utils/coreInternalImport.js
      /Users/dsawali/Desktop/ecadlabs/taquito/node_modules/rx-sandbox/dist/assert/marbleAssert.js
      /Users/dsawali/Desktop/ecadlabs/taquito/node_modules/rx-sandbox/dist/index.js
      test/wallet/increase-paid-storage-operation.spec.ts

      at Resolver.resolveModule (../../node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../../node_modules/rx-sandbox/src/utils/coreInternalImport.ts:7:1)
```

apologies in advance if this isn't a regression caused by `rx-sandbox`. 

Thanks

**Comment by kwonoj** [comment]
I just tried simple example with 7.8.1 and not seeing the error:

https://stackblitz.com/edit/typescript-ys95g5?file=index.ts

If you're experienceing error, please provide a repro that doesn't involve framework / tools to isolate issues to rxjs / rxsandbox.

**Comment by dsawali** [comment]
thanks for the response @kwonoj 

May I ask what TS, Node, NPM version you were trying it on?

**Comment by kwonoj** [comment]
See the stackblitz for the versions. The error above is runtime error so typescript is not relevant.

**Comment by dsawali** [comment]
interesting, is it possible that this might have been an incompatibility with Jest? Not sure if there have been any related issues to that.
