### ISSUE TITLE
Release allow `undefined` as token value. 

### ISSUE THREAD

**Issue by maggie-x** [kwonoj/rx-sandbox#137]
Currently my tests need `undefined` to be allowed as a token value instead of defaulting to the token name. I need this new feature to be released so that I can test properly.

**Comment by kgkma** [comment]
I believe this is with regards to #136. A version bump would be greatly appreciated, thanks!

**Comment by kwonoj** [comment]
https://github.com/kwonoj/rx-sandbox/releases/tag/v1.0.2 has published. Sorry for delay, was out for a day off.

**Comment by kgkma** [comment]
Thank you! No worries at all
