### ISSUE TITLE
RxJS4 advanceBy equivalent

### ISSUE THREAD

**Issue by pkt-zer0** [kwonoj/rx-sandbox#36]
Hi!

The library looks pretty good already, there's only one thing that I'm missing from the RxJS4 testing API: [manually advancing the TestScheduler](https://github.com/robertpenner/RxJS4/blob/master/doc/api/schedulers/virtualtimescheduler.md#rxvirtualtimeschedulerprototypeadvancebytime). Right now, calling `flush()` makes it run all the way through.

The point of that method (as far as I've seen it used, anyway) would be to verify the timing of arbitrary side effects, introduced via a `do()` operator. If there are other / better alternatives for this, I'm also open to suggestions.

**Comment by kwonoj** [comment]
I was actually considered those interfaces but haven't included it, as it makes general scheduler behavior complex but doesn't provide lot of values in marble based testings.

The way I do test side effect is usually mocks, pseudo likes below :
```js

jest.mock('doSide');

const mockedModule = require('doSide');

const source = hot('----a--....')'
source.do(() => doSide())....
flush();

expect(mockedModule.mock.calls).to.have.lengthOf(1);
//other assertions..
```

by this, separate assertion between observable emission / side effects. Above snippet's based on test framework I use, but general approach should be same on other frameworks as well.

**Comment by kwonoj** [comment]
Check `0.0.5` and `advanceTo` interface added. I've picked `To` instead of `By`, let those frame to be absolute number instead of relative - thought in marble it could be bit confusing bit.
