### ISSUE TITLE
Pass in TestMessage as items when using an array for the 'e' function

### ISSUE THREAD

**Issue by xylude** [kwonoj/rx-sandbox#58]
It would be pretty useful to be able to pass in TestMessage as items in an array to the 'e' function.  It could allow developers to supply a frame number and skip having to add marble strings to put the expected message on the correct frame. It would also be useful to be able to use the same function to generate the expected messages and the messages coming out of hot/cold observables.

**Comment by kwonoj** [comment]
`e` is just a wrapper to create array of test message from marble string to assert with testmessage generated from hot / cold observable. https://github.com/kwonoj/rx-sandbox/blob/3eef976b9d5a07d40113e328a4c8562976bc18e8/src/RxSandboxInstance.ts#L10-L14

If you already have test message values, then you can just directly assert it, does not need to use `e` at all.

> It would also be useful to be able to use the same function to generate the expected messages and the messages coming out of hot/cold observables.

That's what `e` does now.
