### ISSUE TITLE
SyntaxError: Unexpected token 'const' on PhantomJS 2.1.1

### ISSUE THREAD

**Issue by nguyenxndaidev** [kwonoj/rx-sandbox#64]
I use PhantomJS 2.1.1 on Windows 7 to run unit tests for my angular 4 project with rx-sandbox 0.0.8 and I get the error: SyntaxError: Unexpected token 'const'. No error on Chrome.

**Comment by kwonoj** [comment]
Phantomjs is deprecated on behalf of headless chrome, and I do not have plan to support old target of browser runtime cannot run latest es specs. You may able to transpile yourself to run under those environment.
