### ISSUE TITLE
Align marble string in Error message with spaces

### ISSUE THREAD

**Issue by nguyenxndaidev** [kwonoj/rx-sandbox#66]
Current error message:
```
Error: 
    "Source:   -(bbb)|"
    "Expected: (aaa)(bbb)|"
```

Expected error message:
```
Error: 
    "Source:   -    (bbb)|"
    "Expected: (aaa)(bbb)|"
```

I think the same frame of 2 streams should be aligned.

**Comment by kwonoj** [comment]
For this reason sandbox accepts spaces between marble tokens to align explicitly. It may possible to align automatically, but requires several edge case handling. Will think about feasibility in a long run.
