### ISSUE TITLE
How to apply test scheduler to nested operators.

### ISSUE THREAD

**Issue by hally9k** [kwonoj/rx-sandbox#84]
I am trying to write an example marble test with rx-sandbox and jest and failing.

See repro -> https://github.com/hally9k/rx-sandbox-jest-example

The observable under test doesn't emit any output. I think the problem is that the test scheduler isn't applied to the delay operator but I can't seem to find how to do that from the readme here. Does rx-sandbox not patch the test scheduler into the operators automagically?

**Comment by kwonoj** [comment]
> Does rx-sandbox not patch the test scheduler into the operators automagically?

In short, answer is no. rx-sandbox only manages test-scheduler observable created by its own interfaces (`hot`, `cold` respectively). This is same behavior to underlying virtual scheduler / or testschedule in rxjs core - for observables created out of scope from testscheduler implementation, it doesn't aware of what scheduler running into and test fixture setup need to inject scheduler manually.

This is somewhat inconvenient indeed, and rxjs core team currently discussing behavior around those between couple of possible mechanisms. rx-sandbox doesn't implement any own custom behavior yet and trying to make core level decision first.

**Comment by hally9k** [comment]
Does rx-sandbox expose it's scheduler so I can mock the import and manually pass it into the operators?

**Comment by kwonoj** [comment]
@hally9k yes - https://github.com/kwonoj/rx-sandbox/blob/master/src/RxSandboxInstance.ts#L21 it's not documented but exposed via type definition.
