### ISSUE TITLE
RxJS 6

### ISSUE THREAD

**Issue by ericadamski** [kwonoj/rx-sandbox#85]
Love this repository!! Awesome package 👏 

Is there a plan to update the dependencies and support RxJS 6?

**Comment by kwonoj** [comment]
Thanks, I think it'll work OOTO only except peerdep warning, but will check and try to bump peerdependency if needed.

**Comment by ericadamski** [comment]
There are a few changes like https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#import-paths that affect the usage of 6 without the rxjs-compat package.

I guess the current solution would be to have a dev dependency of the compat. That will eventually become deprecated.

**Comment by kwonoj** [comment]
Those import paths are relevant as application, sandbox barely have imports from rx affected by it, still need to double check though. I don't consider to use compat as dep / devdep of this pkg.

**Comment by ericadamski** [comment]
@kwonoj I am having a little trouble running `npm test` | `yarn test`, is there something extra I have to do?
![screen shot 2018-05-09 at 8 33 50 am](https://user-images.githubusercontent.com/6516758/39814822-d39a779c-5363-11e8-9b3a-f79034e936fb.png)

**Comment by kwonoj** [comment]
npm install / npm test should work (that's way current ci does) not sure what's missing.

**Comment by ericadamski** [comment]
Ah it seems that I needed to have the `jest-cli` installed globally

**Comment by ericadamski** [comment]
@kwonoj I am so sorry about bother you for all of this 😢 

I have updated all the imports, tests are all 100%, I did a `npm link` to a package I am writing that uses only `RxJS 6.x` without the compat lib and it no longer throws the `missing rxjs-compat` error.

I am attempting to commit this using `npm run commit` so that I can submit a PR to you but I continue to get this error:
![screen shot 2018-05-09 at 9 06 42 am](https://user-images.githubusercontent.com/6516758/39816142-5495afb6-5368-11e8-9d00-825f46c0fe1a.png)

Am I doing something wrong, or did I break something?

Thank you for being so patient.

**Comment by kwonoj** [comment]
including jest-cli error above, I do suspect your npm installation behaves something odd. for example, `any-observable` is definitely dependency in lockfile https://github.com/kwonoj/rx-sandbox/blob/master/package-lock.json#L287 and it should be installed.

**Comment by ericadamski** [comment]
hum, I will do the classic `rm -rf node_modules` and give it another try.

**Comment by ericadamski** [comment]
That didn't work 😢

**Comment by ericadamski** [comment]
Would it be OK to by-pass commitizen so you can pull the code?

**Comment by ericadamski** [comment]
I could just for it and publish it as rx-sandbox-6, if you don't want to move this version away from 5

**Comment by kwonoj** [comment]
Sent out 1.0.0 https://www.npmjs.com/package/rx-sandbox, appreciate for taking time to look into this.
